### ISSUE TITLE
TYPO in getTokenAdressTransfers

### ISSUE THREAD

**Issue by mobilekosmos** [MoralisWeb3/Moralis-JS-SDK#100]
TYPO in [MoralisWeb3Api.js](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/src/MoralisWeb3Api.js)  **getTokenAdressTransfers** should be **getTokenAddressTransfers**

**Comment by Saviour1001** [comment]
Can I fix this @mobilekosmos ? I want to get started making contributions to Moralis

**Comment by mobilekosmos** [comment]
@Saviour1001 I'm not the chief in charge.

**Comment by ErnoW** [comment]
> TYPO in [MoralisWeb3Api.js](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/src/MoralisWeb3Api.js) **getTokenAdressTransfers** should be **getTokenAddressTransfers**

Thanks for letting us know. This file is automatically generated.
We will solve the issue in our api.
