### ISSUE TITLE
Missing property `msg.sender` in `getContractEvents`

### ISSUE THREAD

**Issue by rudolfnep** [MoralisWeb3/Moralis-JS-SDK#1013]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

The SDK feature `getContractEvents` is missing an important property `from` or the transaction sender. It takes an additional blockchain call [`(await provider.getTransaction(hash)).from`] to retrieve that data. For results that produce many records, it simply makes everything slower.

Do you have any plans to add `from` property to the `getContractEvents` and `getContractLogs` functions?

**Comment by ErnoW** [comment]
I'm not sure what you mean. You get the `from` address back under the `data` attribute. 

For example, the response could return:
```
    [{
      "transaction_hash": "0x34d2376a3b379abcaf8d74ad2bd6a08dc1e0a70f3b0472dcb957626ec73b86cb",
      "address": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
      "block_timestamp": "2023-02-13T09:22:11.000Z",
      "block_number": "16618909",
      "block_hash": "0x498e6b625cb1aaa9ed6406e32a983b1ccfcce7bdfa1d37bc1d184a0bb6ba3d4c",
      "data": {
        "from": "0x28c6c06298d514db089934071355e5743bf21d60",
        "to": "0x0434b69fdc87d02a2633520bf0a84c33d581b0ba",
        "amount": "9380000000000000000"
      }
    }]
```

For more info see  https://docs.moralis.io/web3-data-api/reference/get-contract-events

**Comment by ErnoW** [comment]
I see now what you mean. I think that this is not possible in 1 request at the moment. It's a good use-case to include it, I will forward the request to the api team, to see if it makes sense to include it in these responses.

Closing this issue as it's not a bug in the SDK.
