### ISSUE TITLE
moralis@2.14 problem with type in package.js

### ISSUE THREAD

**Issue by 0xch** [MoralisWeb3/Moralis-JS-SDK#1022]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

There is a problem during initialization of Moralis:
``
import Moralis from 'moralis';
``

The problem exists only in v2.14, in v2.13 and earlier everything works well.

```
(node:78159) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/var/www/test/node_modules/moralis/lib.esm/index.js:1
import { Streams } from '@moralisweb3/streams';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

### Steps + code to reproduce

Install a v2.14 (newest) and import it to js file (e.g. `abc.js`) having `package.json` with set `"type":"module"`
```
import Moralis from 'moralis';
```

### Environment

v2.14

**Comment by b4rtaz** [comment]
I've just confirmed this problem. We will look at this ASAP.

**Comment by b4rtaz** [comment]
@0xch Could you check the problem on the `2.15.0` version?

**Comment by 0xch** [comment]
@b4rtaz Yes, it works now. Thank you.
