### ISSUE TITLE
Testing Moralis SDK Locally

### ISSUE THREAD

**Issue by Hussainzz** [MoralisWeb3/Moralis-JS-SDK#1050]
## Contribute
i am new to the open-source , i wanted to understand how i can test the packages locally. i did find the CONTRIBUTING.md
how to go about testing ti after i run `yarn dev`

https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/CONTRIBUTING.md

**Comment by ErnoW** [comment]
Hi, great to hear that you want to contribute. We will update the CONTRIBUTING.md, it is outdated.

What you need to do is:

1. Install dependencies in the root: `yarn install`
2. Build all the packages via `yarn build` in the root

Then all packages and demos should be ready to use. To test the SDK and its packages you can:
- Run the tests in one of the packages, `cd packages/evmApi` and `yarn test` for example to run all the tests of evmApi (or you can run `yarn test` in the root to run the tests of all the packages)
- Or if you want to play around with one of the demos you can open up one of the demos like `cd demos/cli` and `yarn start` (check the package.json for each demo to see what scripts are available, some have `start`/`build`/`dev`/`test`)

I hope this helps.

**Comment by BillyG83** [comment]
hey @ErnoW thanks for the super fast reply. This is @Hussainzz one of the coolest guys in our community 🥳

**Comment by Hussainzz** [comment]
Worksss   🥳 🥳 🥳 🥳 🥳 🥳 🥳 🥳 Thank you So much @ErnoW , looking forward to learn and contribute

**Comment by Hussainzz** [comment]
@ErnoW  Let me introduce you to @BillyG83, the most humble and down-to-earth person I have ever met. He is a man with a good heart  ❤️

**Comment by Hussainzz** [comment]
I am closing this issue thanks @ErnoW
