### ISSUE TITLE
Option to pass baseUrl to EvmApi

### ISSUE THREAD

**Issue by shrpne** [MoralisWeb3/Moralis-JS-SDK#1080]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation
Currently it's impossible to override baseUrl in EvmApi

### Feature / Enhancement Description
Please add option to pass custom baseUrl to [EvmApi](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/packages/evmApi/src/EvmApi.ts) `create` function and constructor

**Comment by b4rtaz** [comment]
Hello @shrpne! Could you describe a bit reasons why you need it?

**Comment by shrpne** [comment]
I use Moralis SDK on the web, i can't use default api url `deep-index.moralis.io/api` for few reasons:
- it doesn't return CORS headers
- i can't expose apiKey in client side js

So i use thin proxy, which adds apiKey to requests and adds CORS headers to responses. And i need to pass url of my proxy to SDK

**Comment by b4rtaz** [comment]
We like this idea. We will add this feature soon. Meanwhile you can fork the repo and work on the local version.

**Comment by b4rtaz** [comment]
Hello @shrpne! Could you check the 2.19.0 version?

```ts
  Moralis.start({
    apiKey: '<API_KEY>',
    evmApiBaseUrl: 'https://my-website.com/moralis-api'
  });
```

**Comment by shrpne** [comment]
Everything works fine, thank you!
