### ISSUE TITLE
Moralis Streams switch to paused state by themselves for unknown reason.

### ISSUE THREAD

**Issue by h4nz4** [MoralisWeb3/Moralis-JS-SDK#1108]
Hello. 

I have been experimenting with Moralis on a toy project. I have created a stream manually in the Admin panel, then added an address programmatically using the Node.js SDK. The stream becomes paused randomly, by itself, after some amount of time. **Why does this happen and how can it be prevented? I did not find any explaination in the documentation.**

 Thanks!

**Comment by b4rtaz** [comment]
Hi @h4nz4! Thanks for reporting. We are looking at this.

**Comment by b4rtaz** [comment]
@h4nz4 are you certain that you're not exceeding your account limits?

**Comment by h4nz4** [comment]
The account limits cannot be the culprit here. The streams simply pause by themselves.


￼

**Comment by b4rtaz** [comment]
I've executed the below code and I'm receiving data without any problems for an hour now.

Maybe your hook throws an error. The webhook should return HTTP 200.

```ts
import Moralis from 'moralis';
import { EvmChain } from '@moralisweb3/common-evm-utils';

async function main() {
  Moralis.start({
    apiKey: '<API_KEY>',
  });

  const stream = await Moralis.Streams.add({
    chains: [EvmChain.ETHEREUM],
    description: 'test sdk',
    tag: 'test',
    webhookUrl: '<WEBHOOK_URL>',
    abi: [
      {
        anonymous: false,
        inputs: [
          {
            indexed: true,
            name: 'from',
            type: 'address',
          },
          {
            indexed: true,
            name: 'to',
            type: 'address',
          },
          {
            indexed: false,
            name: 'value',
            type: 'uint256',
          },
        ],
        name: 'Transfer',
        type: 'event',
      },
    ],
    topic0: ['Transfer(address,address,uint256)'],
    includeContractLogs: true,
  });

  console.log('stream', stream.toJSON());

  const addr = await Moralis.Streams.addAddress({
    id: stream.result.id,
    address: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
  });

  console.log('addr', addr.toJSON());
}

main();
```

**Comment by b4rtaz** [comment]
https://docs.moralis.io/streams-api/evm/error-handling

```
Your Stream can enter into error state on the following 2 scenarios:

- Your webhook success-rate is below 70%
- Your server is not consuming the webhooks  (...)
```

**Comment by h4nz4** [comment]
Error state, or also paused state? Please not that the streams went into the paused state.On 28 Apr 2023, at 12:28, Bart Tadych ***@***.***> wrote:﻿
https://docs.moralis.io/streams-api/evm/error-handling
Your Stream can enter into error state on the following 2 scenarios:

- Your webhook success-rate is below 70%
- Your server is not consuming the webhooks  (...)

**Comment by b4rtaz** [comment]
@h4nz4 have you solved the problem?

**Comment by b4rtaz** [comment]
What a message do you have in the `statusMessage` after the problem occurs?

**Comment by h4nz4** [comment]
Where can this *statusMessage* be observed?

V V čet., 11. maj 2023 ob 11:13 je oseba Bart Tadych <
***@***.***> napisala:

**Comment by b4rtaz** [comment]
You can read it from by calling for the list of your all streams.

```ts
  const streams = await Moralis.Streams.getAll({
    limit: 10
  })
  console.log(streams.result[0].statusMessage);
```

**Comment by h4nz4** [comment]
I checked now. The paused streams have statusMessage "Disconnected from Demo"

**Comment by b4rtaz** [comment]
I have this status when:

* I've created a demo stream from the admin panel.
* The stream is in the **demo mode** <img width="186" alt="image" src="https://github.com/MoralisWeb3/Moralis-JS-SDK/assets/12797776/c7a93176-e892-4226-b0a7-b5af58c90cd0">
* I've closed the browser tab with the preview of the stream.

Are you sure you have created a stream by the SDK? Please be sure that, you don't have the admin panel opened in the background.

**Comment by h4nz4** [comment]
The streams I used were created manually in the admin panel. They weren't
created from the SDK. They have always been in demo mode.
Could the latter cause the pausing behavior?

V V čet., 11. maj 2023 ob 12:40 je oseba Bart Tadych <
***@***.***> napisala:

**Comment by b4rtaz** [comment]
For the demo mode it's not possible. The demo mode is only for testing purposes. You need switch the mode to `prod`.

**Comment by h4nz4** [comment]
I see. So this could be the origin of the problems all along?

V V čet., 11. maj 2023 ob 13:02 je oseba Bart Tadych <
***@***.***> napisala:

**Comment by b4rtaz** [comment]
@h4nz4 Have you tested it? Can we close this issue?

**Comment by b4rtaz** [comment]
@h4nz4 can we close this issue?

**Comment by b4rtaz** [comment]
Due to inactivity I close this issue. If the problem still occurs, please open a new one.
