### ISSUE TITLE
Error: undefined Unable to resolve module moralis/common-evm-utils in React-Native project

### ISSUE THREAD

**Issue by chachaxw** [MoralisWeb3/Moralis-JS-SDK#1124]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I got this error when I tried to use @moralisweb3/react in my project, I have installed `moralis` and `@moralisweb3/react`, but I still got this error.

```
 ERROR  [Error: undefined Unable to resolve module moralis/common-evm-utils from /Users/chacha/Develop/lenstalk-app/node_modules/@moralisweb3/react/lib/hooks/evmApi/generated/useEvmContractEvents.js: moralis/common-evm-utils could not be found within the project or in these directories:
  node_modules
  53 | exports.useEvmContractEvents = void 0;
  54 | var moralis_1 = __importDefault(require("moralis"));
> 55 | var common_evm_utils_1 = require("moralis/common-evm-utils");
     |                                   ^
  56 | var react_1 = require("react");
  57 | var utils_1 = require("../../utils");
  58 | var validateParams_1 = require("../../../utils/validateParams");]

```

I checked node_modules, there's a lot of @moralisweb3 modules. Can someone help me?

![Screenshot 2023-05-14 at 21 37 48](https://github.com/MoralisWeb3/Moralis-JS-SDK/assets/9986672/b16677c8-e8f7-4a95-8188-6ef93916b375)

### Steps + code to reproduce

![IMG_2404](https://github.com/MoralisWeb3/Moralis-JS-SDK/assets/9986672/42332412-05b7-41c0-84de-1b399f00b397)

Just installed these packages in react-native project, and it will reproduce the issue.

```
  // package.json
  "@moralisweb3/common-core": "^2.20.0",
  "@moralisweb3/common-sol-utils": "^2.20.0",
  "@moralisweb3/evm-api": "^2.20.0",
  "@moralisweb3/react": "^2.20.0",
```

### Environment

Server

- Moralis server version: `No Server`

Client

- Moralis SDK version: `2.20.0`
- Operating system: `Mac OS`
- Browser: `React-Native`

**Comment by b4rtaz** [comment]
@chachaxw Have you solved the problem?

**Comment by chachaxw** [comment]
@b4rtaz Yeah, I have solved this problem, and it seems the latest version support react native now.
