### ISSUE TITLE
@moralisweb3/common-evm-utils -> Arbitrum Goerli Chain Object

### ISSUE THREAD

**Issue by Guceri** [MoralisWeb3/Moralis-JS-SDK#1141]
Within the `@moralisweb3/common-evm-utils`  npm package, there is `EvmChain` which should produce a Moralis Chain Object such as this (example is for Arbtitrum mainnet):

services-event-streamer-1     | MORALIS CHAIN OBJECT EvmChain {
services-event-streamer-1     |   _value: '0xa4b1',
services-event-streamer-1     |   _chainlistData: {
services-event-streamer-1     |     name: 'Arbitrum One',
services-event-streamer-1     |     chainId: 42161,
services-event-streamer-1     |     shortName: 'arb1',
services-event-streamer-1     |     chain: 'ETH',
services-event-streamer-1     |     networkId: 42161,
services-event-streamer-1     |     nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
services-event-streamer-1     |     rpc: [
services-event-streamer-1     |       'https://arbitrum-mainnet.infura.io/v3/$%7BINFURA_API_KEY%7D',
services-event-streamer-1     |       'https://arb-mainnet.g.alchemy.com/v2/$%7BALCHEMY_API_KEY%7D',
services-event-streamer-1     |       'https://arb1.arbitrum.io/rpc'
services-event-streamer-1     |     ],
services-event-streamer-1     |     faucets: [],
services-event-streamer-1     |     explorers: [ [Object], [Object] ],
services-event-streamer-1     |     infoURL: 'https://arbitrum.io/',
services-event-streamer-1     |     parent: { type: 'L2', chain: 'eip155-1', bridges: [Array] }
services-event-streamer-1     |   }
services-event-streamer-1     | }

Moralis now has support for arbitrum goerli (chainId = 421613), but when we do EvmChain.create(421613)  it returns null. Additionally, there is no direct member of `Evmchain` for arbitrum goerli like there is for arbitrum (ie. `EvmChain.ARBITRUM`).  

The thought was that `EvmChain.create` was the path to take, but it returns `null`

**Comment by nikkatalnikov** [comment]
so, that's basically "add Arbitrum Goerli support to common-utils".

**Comment by b4rtaz** [comment]
Hi @Guceri, @nikkatalnikov! We will add new chains as soon as possible. I'll let you know.

**Comment by b4rtaz** [comment]
@nikkatalnikov @Guceri could you check the `2.22.1` version?

**Comment by Guceri** [comment]
> @nikkatalnikov @Guceri could you check the `2.22.1` version?

Thank you for the quick fix.  I used 2.22.1 for both `moralis` and `@moralisweb3/common-evm-utils` along with `EvmChain.ARBITRUM_TESTNET` and everything appears to be working.
