### ISSUE TITLE
New web3 version 1.6.1 to be updated in Moralis

### ISSUE THREAD

**Issue by uvindu9412** [MoralisWeb3/Moralis-JS-SDK#121]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

With the current web3 version (1.6.0) used in moralis we are not getting success callback/ receipt with walletconnect

### Feature / Enhancement Description

The web3 version in moralis should be updated to 1.6.1

### Example Use Case
```
 const sellNftContract = new web3.eth.Contract(NFT_CONTRACT.abi, address)
    try{
      let res = await sellNftContract.methods.testmethod(userAddress, 'test').send({ from: userAddress,price:10})
         .on('transactionHash', function(hash){
           console.log(hash)
       }).on('receipt', function(receipt){
         console.log(transactionHash)
     })
    } catch (e) {
      console.log(e);
    }
```
If walletconnect is being used reciept wont be retrieved. How ever this has been fixed in web3 1.6.1 version
### Alternatives / Workarounds

-

### 3rd Party References

-

**Comment by ErnoW** [comment]
We are currently migrating out the dependency on web3, so you can specify the web3 version yourself. Expect this to release very soon :)
