### ISSUE TITLE
Add ethers support

### ISSUE THREAD

**Issue by PatrickAlphaC** [MoralisWeb3/Moralis-JS-SDK#123]
### Checklist

- [ x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ x ] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Right now, the development world is migrating to an ethers/hardhat world. Having ethers supported would make it easier to jump into these projects with hardhat implementations.

**Comment by ErnoW** [comment]
We are working on this feature, to let you specify whatever library you want, expect it very soon 😏

**Comment by adbario** [comment]
> We are working on this feature, to let you specify whatever library you want, expect it very soon 😏

This is great news @ErnoW 👍 Do you have any estimate when this would be ready to ship out?

**Comment by ErnoW** [comment]
@PatrickAlphaC  @adbario 
This functionality is now live in the beta build. See: https://github.com/MoralisWeb3/Moralis-JS-SDK/issues/179

This includes Ethers.js support out of the box (and you can optionally switch to use Web3.js)

**Comment by PatrickAlphaC** [comment]
LETS GOOOOOOO
