### ISSUE TITLE
Moralis.authenticate() is error

### ISSUE THREAD

**Issue by Breathe-97** [MoralisWeb3/Moralis-JS-SDK#124]
I use it on vue.
Example:
import Moralis from 'moralis/dist/moralis.min.js';
if you use api: Moralis.authenticate()
errmsg is : Uncaught (in promise) TypeError: t2 is not a constructor
So.I tryit
import Moralis from 'moralis/dist/moralis.js'
use api:Moralis.authenticate()
errmsg is : Uncaught (in promise) TypeError: MWeb3 is not a constructor
I don't know why.But I want to get help with feedback.
Thanks.

**Comment by Breathe-97** [comment]
I found the cause.
I think moralis can automatically introduce web3
But actually I need to introduce it separately
So
<script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
And
import moralis from 'moralis/dist/moralis.min.js'
Then it's normal.

**Comment by ErnoW** [comment]
Yes, that is correct, you need to provide the web3 library manually.
This is expected behavior.
Glad that you figured it out. Happy buidling
