### ISSUE TITLE
Response types are not correct since v0.0.157

### ISSUE THREAD

**Issue by SuPuL** [MoralisWeb3/Moralis-JS-SDK#148]
### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [X] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

Since v0.0.156 we get typescript errors while building.

### Steps + code to reproduce

Build using typescript. 

### Actual Outcome

node_modules/moralis/types/generated/web3Api.d.ts:1970:194 - error TS2339: Property '200' does not exist on type '{ 201: unknown; }'.
1970     syncNFTContract: (options: operations["syncNFTContract"]["parameters"]["query"] & operations["syncNFTContract"]["parameters"]["path"]) => Promise<operations["syncNFTContract"]["responses"]["200"]["content"]["application/json"]>;

### Expected Outcome

The types for the response code are matching. So it should be 201 here.

### Environment

^v0.0.157

Server
not needed

Client

- Moralis SDK version: `^v0.0.157`
- Operating system: `mac`

### Logs

see outcome

**Comment by ErnoW** [comment]
Thanks for reporting, fixed in https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/152
