### ISSUE TITLE
Moralis depends on the process object when imported 

### ISSUE THREAD

**Issue by GuiBibeau** [MoralisWeb3/Moralis-JS-SDK#153]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

When running in a svelte kit vitejs environment, moralis depends on process.env which is undefined client side. This causes the instanciation of the library to not function properly when the svelte code is compiled and served to the client

### Steps + code to reproduce

```
npm init svelte@next my-app
cd my-app
npm install
npm install moralis --save
npm run dev
touch moralisProvider.js
```

add the following code to the file, pass your own server keys instead of the env vars. (They are properly defined in my server, this is not the issue)

```
import Moralis from 'moralis';

export const moralisProvider = async () => {
	const serverUrl = import.meta.env.VITE_MORALIS_SERVER_URL;
	const appId = import.meta.env.VITE_MORALIS_APP_ID;

	if (typeof serverUrl !== 'string' || typeof appId !== 'string') {
		throw new Error('Missing Moralis server url or app id');
	}

	await Moralis.start({ serverUrl, appId });
};
```
in `src/routes/index.svelte` call the function. 

```
if (typeof window !== 'undefined') {
moralisProvider()
}
```

svelte-kit is an isomorphic rendering engine for svelte that can render html on the server, ensure you are not in the server environment with the if condition otherwise this will fail and cause another unrelated issue that is not of concern to this one.

Real life example is in this PR https://github.com/gamblefi/gamble/pull/14/files#diff-e659bdba229a88ffb053961749788c7fea8180d342ca946ab36de7145aa865e6R75

### Actual Outcome

The call to Moralis.Start runs into an inappropriate check for process.env instead of using optional chaining. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

<img width="494" alt="Screen Shot 2021-12-19 at 8 01 21 PM" src="https://user-images.githubusercontent.com/22625602/146697940-dacac558-1223-4fd7-b274-f0e2923c7a87.png">

### Expected Outcome

client is instanciated regularly

### Environment

svelte kit on latest environment and latest moralis npm version

Server

- Moralis server version: `latest`

Client

- Moralis SDK version: `latest`
- Operating system: mac osx m1
- Browser: chromium

### Logs
```
util.js:109 Uncaught (in promise) ReferenceError: process is not defined
    at ../../node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-ENMAWK7U.js?v=d2085534:36:44)
    at ../../node_modules/moralis/node_modules/web3-core-requestmanager/lib/index.js (index.js:20:25)
    at __require2 (chunk-ENMAWK7U.js?v=d2085534:36:44)
    at ../../node_modules/moralis/node_modules/web3-core/lib/index.js (index.js:22:24)
    at __require2 (chunk-ENMAWK7U.js?v=d2085534:36:44)
    at ../../node_modules/moralis/node_modules/web3/lib/index.js (index.js:29:12)
    at __require2 (chunk-ENMAWK7U.js?v=d2085534:36:44)
    at ../../node_modules/moralis/lib/browser/MoralisWeb3.js (MoralisWeb3.js:57:35)
    at __require2 (chunk-ENMAWK7U.js?v=d2085534:36:44)
../../node_modules/util/util.js @ util.js:109
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/node_modules/web3-core-requestmanager/lib/index.js @ index.js:20
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/node_modules/web3-core/lib/index.js @ index.js:22
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/node_modules/web3/lib/index.js @ index.js:29
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/lib/browser/MoralisWeb3.js @ MoralisWeb3.js:57
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/lib/browser/ParseUser.js @ ParseUser.js:51
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/lib/browser/ParseACL.js @ ParseACL.js:25
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/lib/browser/decode.js @ decode.js:19
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/lib/browser/Parse.js @ Parse.js:31
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
../../node_modules/moralis/index.js @ index.js:1
__require2 @ chunk-ENMAWK7U.js?v=d2085534:36
(anonymous) @ dep:moralis:1
await in (anonymous) (async)

```

**Comment by ivan-liljeqvist** [comment]
Hm we will check
I’ll see if we have someone with svelte experience 

if you can submit a fix as  PR yourself that will fix this issue - feel free

**Comment by jakubdonovan** [comment]
4 months since the last commend and the issue remains unsolved. @ivan-liljeqvist did you guys have a chance to have a look at this at all

**Comment by ErnoW** [comment]
Closing, as it's outdated since we moved to v2
