### ISSUE TITLE
 Property 'parameters' does not exist on type '{ responses: { 200

### ISSUE THREAD

**Issue by romain130492** [MoralisWeb3/Moralis-JS-SDK#159]
### Checklist

* Im using `morallis` on a typecript vue repo,
*     "moralis": "0.0.90",
* I keep getting this error `Error in /node_modules/moralis/types/generated/web3Api.d.ts(1714,56):   TS2339: Property 'parameters' does not exist on type '{ responses: { 200: { content: { "application/json": { path: string; }[]; }; }; }; requestBody: { content: { "application/json": { path: string; content: string; }[]; }; }; }'.`
* My implementation 
```js
 import Moralis from 'moralis'
  Moralis.initialize("API key");
   Moralis.serverURL = "server url";
 const user = await Moralis.Web3.authenticate({provider:"walletconnect", chainId:137 })
```

I added that in my typescript config : 
```
  "exclude": [
    "node_modules/*"
  ]
```
* now the projects starts, however when using anything related `Morallis` method well im getting that error
* It works using a vue 3 project without typescript
Thanks

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ ] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Environment

Server

- Moralis server version: `FILL_THIS_OUT`

Client

- Moralis SDK version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Browser: `FILL_THIS_OUT`

**Comment by laxmikanta415** [comment]
Hey @romain130492 can you share the code with same set up on JSFiddle or similar environment, so i can help you on this.

**Comment by ErnoW** [comment]
moralis v0.0.90 is quite outdated. This issue has alraedy been fixed.
Please update your package to make sure to run the latest version.
