### ISSUE TITLE
Can't autocomplete SDK code when using moralis/node in VS Code

### ISSUE THREAD

**Issue by Vivraan** [MoralisWeb3/Moralis-JS-SDK#183]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

Unable to see autocompletion work for `moralis/node`.

### Steps + code to reproduce

0. Use VS Code + Powershell 7.2.1
1. `npm init && npm install moralis`
2. Create `tsconfig.json` with contents:
```json
{
    "compilerOptions": {
        "target": "es2020",
        "module": "commonjs",
        "lib": [
            "es5",
            "es6",
            "dom"
        ],
        "removeComments": true,
        "rootDir": "./src",
        "outDir": "./dist",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true
    }
}
```
3. Create `global.d.ts` with the following contents:

```ts
declare const { Moralis }: typeof import('moralis/node');
```
4. Create a file with `.ts` extension and try to trigger autocomplete by typing `Moralis.`

(Assumption) may also be reproducible with JS.

### Actual Outcome

No autocompletion works unless the import is for `'moralis'`.

### Expected Outcome

Autocomplete works and I live a better day!

### Environment

Server

- Moralis server version: `0.0.326`

Client

- Moralis SDK version: `0.0.183`
- Operating system: `Windows 11 Home 21H2 (build 22000.376)`
- Browser: `Brave 1.34.80 Chromium: 97.0.4692.71`

### Logs

None.

**Comment by ErnoW** [comment]
Moralis types are exported directly, no need for a declaration file.
Tested a simple node app with the following config, which works:
```
{
  "compilerOptions": {
    "target": "es5" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
    "module": "commonjs" /* Specify what module code is generated. */,
    "rootDir": "./src" /* Specify the root folder within your source files. */,
    "baseUrl": "./src" /* Specify the base directory to resolve non-relative module names. */,
    "outDir": "./lib" /* Specify an output folder for all emitted files. */,
    "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */,
    "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
    "strict": true /* Enable all strict type-checking options. */,
    "useUnknownInCatchVariables": false /* Type catch clause variables as 'unknown' instead of 'any'. */,
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  },
  "include": ["src"]
}
```

Then
```
import Moralis from "moralis/node";
```
will give auto completion for example for `Moralis.start`

---

If it still does not work, then please submit a question in our forum. We are more active with support and developers over there :)

**Comment by Vivraan** [comment]
> Moralis types are exported directly, no need for a declaration file. Tested a simple node app with the following config, which works:
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es5" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
>     "module": "commonjs" /* Specify what module code is generated. */,
>     "rootDir": "./src" /* Specify the root folder within your source files. */,
>     "baseUrl": "./src" /* Specify the base directory to resolve non-relative module names. */,
>     "outDir": "./lib" /* Specify an output folder for all emitted files. */,
>     "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */,
>     "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
>     "strict": true /* Enable all strict type-checking options. */,
>     "useUnknownInCatchVariables": false /* Type catch clause variables as 'unknown' instead of 'any'. */,
>     "skipLibCheck": true /* Skip type checking all .d.ts files. */
>   },
>   "include": ["src"]
> }
> ```
> 
> Then
> 
> ```
> import Moralis from "moralis/node";
> ```
> 
> will give auto completion for example for `Moralis.start`
> 
> If it still does not work, then please submit a question in our forum. We are more active with support and developers over there :)

I'm trying to work with Moralis Cloud Code.
