### ISSUE TITLE
Consider switch to TypeScript to build large scale project insteal of Javascript.

### ISSUE THREAD

**Issue by noberk** [MoralisWeb3/Moralis-JS-SDK#197]
![image](https://user-images.githubusercontent.com/26300918/149795027-c88e7e93-9043-40fa-9ccb-7fd1899a189a.png)

Typescript will help you to generate d.ts file automatically after compiling Javascript. you don't need to write type declaration again

**Comment by ErnoW** [comment]
We have improved Typescript in the latest version.
We had the typings for Moralis.Web3.enableWeb3() but not for Moralis.enableWeb3(). (both methods work)

This has been resolved now.
