### ISSUE TITLE
Cannot enable WalletConnect: dependency "@walletconnect/web3-provider" is missing

### ISSUE THREAD

**Issue by worldpiontek** [MoralisWeb3/Moralis-JS-SDK#215]
`
user = await Moralis.authenticate({"provider: "walletconnect"})
`

is giving an **error** : Cannot enable WalletConnect: dependency "@walletconnect/web3-provider" is missing

SDK has been added

- <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
- <script src="https://unpkg.com/moralis/dist/moralis.js"></script>
- <script src="https://github.com/WalletConnect/walletconnect-monorepo/releases/download/1.6.2/web3-provider.min.js"></script>

NB: 3 or 2 days ago walletconnect auth is working fine

**Comment by ivan-liljeqvist** [comment]
Please post in https://forum.moralis.io thanks

**Comment by ChristopherTrimboli** [comment]
I have same issue today, feedback on the forums thing... issues are being addressed poorly.

I go to forums, search around for this, can't find it... I recommend actually just using these Github issues reports as devs use this the most.

I guess we will go to forums and try and find info.
