### ISSUE TITLE
Bundle size since version 1 is quite massive 

### ISSUE THREAD

**Issue by kantorcodes** [MoralisWeb3/Moralis-JS-SDK#237]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

![4A5561B5-5A35-4AC0-BC87-69BE98DBF30D](https://user-images.githubusercontent.com/6068672/151676599-c53c5e57-ccbc-4b46-9aa4-0f05b87787fd.png)

### Steps + code to reproduce

 - Create a basic webpack setup
 - import Moralis to the application
 - Add `webpack-bundle-analyzer` to webpack config
 - observe bundle size is very large

### Actual Outcome

 - Bundle size > 1.5mbs 

### Expected Outcome

 - Bundle size <= 100kb 

### Environment

 - esnext

Client

- Moralis SDK version: `1.2.3`
- Operating system: `OSX
- Browser: `Brave`

**Comment by ivan-liljeqvist** [comment]
Hi we are always looking for ways to shrink it

We optimized it a lot recently and will continue to find ways

if you think something concrete in the code is excessive or can be shrinked - please create an issue for that

I’ll close this in the meanwhile as we won’t be able to work on this general comment

**Comment by kantorcodes** [comment]
> Hi we are always looking for ways to shrink it
> 
> We optimized it a lot recently and will continue to find ways
> 
> if you think something concrete in the code is excessive or can be shrinked - please create an issue for that
> 
> I’ll close this in the meanwhile as we won’t be able to work on this general comment
> 
> The actual sizes of current version can be seen here: https://bundlephobia.com/package/moralis
> 
> currently core moralis it’s 228kb gzipped

I am seeing 1.5mbs in the bundle size, much higher than 228kb. Is this because of webpack5?

**Comment by kantorcodes** [comment]
@ivan-liljeqvist

**Comment by ErnoW** [comment]
@kantorcodes We have plans on using rollup, splitting logic up in packages, and other dev-improvements (like native Typescript). But it has a big impact and will be done probably in the next major version.

In the meantime, we still use gulp and find ways to optimize the bundle without breaking changes.
