### ISSUE TITLE
Type Definitions | Unable to Reference from Global Declaration File

### ISSUE THREAD

**Issue by charles-salmon** [MoralisWeb3/Moralis-JS-SDK#25]
## Problem Specification

I currently reference the Moralis type definitions like so:

```
/// <reference types="moralis" />
```

in a global declaration file (`*.d.ts`).

This only seems to be possible if I reference v0.0.35 or earlier of the Moralis SDK.

## Technical Details

I have noted that the way in which the `Moralis` namespace is exported was changed in v0.0.36. In v0.0.35, this was exported like so:

```
export = Moralis
```

but it is now exported using:

```
export default Moralis
export type Moralis = typeof Moralis
```

## Additional Context

The reason why I wish to reference the Moralis SDK type definitions, without importing the Moralis SDK directly, is because I am currently referencing the Moralis SDK via a CDN, but still wish to benefit from type completions. This makes front-end projects, using Vite, somewhat easier to bundle (without battling against the need for numerous polyfills).

**Comment by ErnoW** [comment]
Closing this issue, as it's not something we can fix now. Changing back the type definitions will break other implementations when using a package manager. The next major release will be written in Typescript, so hopefully this issue will not be a problem then anymore.
