### ISSUE TITLE
saveIPFS() function is not working as expected

### ISSUE THREAD

**Issue by JJ810** [MoralisWeb3/Moralis-JS-SDK#260]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

`saveIPFS()` function is not saving file correctly to IPFS and since this is an issue on production I would like to fix this issue as soon as possible. thanks in advance.

```js
const res = await file.saveIPFS()
console.log(await res.ipfs(), await res.hash())
```

`res.ipfs()` returns link to the image - i.e: https://ipfs.moralis.io:2053/ipfs/QmXs57mbGbhZiEGv3DqAJKwemi36C1TFrqyFzQd6C44B1L
instead of JSON as in [this document](https://docs.moralis.io/moralis-server/files/ipfs) result - https://ipfs.moralis.io:2053/ipfs/QmUfpsyqc4hwozotRo4woyi5fJqvfcej5GcFvKiWoY6xr6

### Steps + code to reproduce
```
const file = new Moralis.File(media[0].name, media[0])
const res = await file.saveIPFS()
```

### Actual Outcome

Getting ipfs link just returns the image instead JSON.

### Expected Outcome
Get JSON object from `saveIPFS()` method.

### Environment

Server

- Moralis server version: `0.0.345`

Client

- Moralis SDK version: `1.3.1`
- Operating system: `MacOS Monterey`
- Browser: `Chrome`

**Comment by ErnoW** [comment]
I'm not sure what the issue exactly is.

You say "function is not saving file correctly to IPFS", but in your example you say that the link returns the image. So it is working then, right?

I'm not sure if I get you correctly, please be more specific in what you expect, and what you get. From your message it seems that you want to upload an image, but expecting a JSON to return? 

How it works is; if you save an image, then the link IPFS link will contain the image.
If you save an json, then the IPFS link will contain the JSON

**Comment by ErnoW** [comment]
Also note that the best place to ask for support is at https://forum.moralis.io/
As we have a team of developers and support, that check issues daily.
