### ISSUE TITLE
Properties are deleted from options passed by client in MoralisWeb3Api and MoralisSolanaApi

### ISSUE THREAD

**Issue by jfrazier-eth** [MoralisWeb3/Moralis-JS-SDK#267]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [X] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

Properties are deleted from the options object passed by the client in the `Web3API`

### Steps + code to reproduce

Pass required options to a call to the `Web3API` call such as: 
```
const options = { address: '0x1a92f7381b9f03921564a437210bb9396471050c', chain: '0x1' };
const metaData = await Moralis.Web3API.token.getNFTMetadata(options);
```

### Actual Outcome

After the call, the address (and other required properties) are deleted from the options object passed by the client. 
```
// options is now { chain: '0x1' }
```

### Expected Outcome

I expect the options object not to be modified so it can be passed in subsequent calls.
```
const options = { address: '0x1a92f7381b9f03921564a437210bb9396471050c', chain: '0x1' };
const metaData = await Moralis.Web3API.token.getNFTMetadata(options);

/** 
 *  options should still have an address property so the next line
 *  won't throw an error due to the address not being provided
 */
const tokenIds = await Moralis.Web3API.token.getAllTokenIds(options);
```

### Environment

Server

- Moralis server version: `0.0.345`

Client

- Moralis SDK version: `1.3.2`
- Operating system: `MacOS Monterey`
- Browser: `Chrome`

**Comment by ErnoW** [comment]
Fixed in 1.3.5
