### ISSUE TITLE
NPM Error: Refusing to install package with name "moralis" under a package also called "moralis"

### ISSUE THREAD

**Issue by carloswalterbr** [MoralisWeb3/Moralis-JS-SDK#268]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

NPM Error: Refusing to install package with name "moralis" under a package also called "moralis"

### Steps + code to reproduce
npm i moralis

npm i moralis

### Actual Outcome

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "moralis" under a package
npm ERR! also called "moralis". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
### Expected Outcome

Installation done.

### Environment

NodeJS v.12.18.0 on MacOS Catalina 10.15.7

Server

- Moralis server version: 0.0.345

Client

- Moralis SDK version: v.1.3.2
- Operating system: MacOS Catalina 10.15.7
- Browser: Brave

### Logs

[2022-02-16T12_54_02_273Z-debug.log](https://github.com/MoralisWeb3/Moralis-JS-SDK/files/8080074/2022-02-16T12_54_02_273Z-debug.log)

**Comment by YosephKS** [comment]
@carloswalterbr so the name of your project in `package.json` is also `moralis`?

**Comment by carloswalterbr** [comment]
It's possible. I'll check (and if so, sorry for wasting your time)

**Comment by carloswalterbr** [comment]
:) Yes, that was it. Thanks.
