### ISSUE TITLE
event sync broken for events with indexed address[] argument

### ISSUE THREAD

**Issue by dvinubius** [MoralisWeb3/Moralis-JS-SDK#277]
Events with arguments of type `indexed address[]` cannot be properly synced. The table is created but never populated.

- [x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I've worked quite a bit on the issue, making sure I've got everything set up properly.

Given the code below, after setting up Event Sync I get DB table entries for all events but the ones that have an `indexed address[]` argument

### Steps + code to reproduce

![Screenshot 2022-03-01 at 21 27 57](https://user-images.githubusercontent.com/32189942/156236542-a58cdad2-461c-40d6-ab97-b6dea660b830.png)

### Environment

- Moralis server version: `0.0.347`

**Comment by ErnoW** [comment]
Please post issues for support at forum.moralis.io, we have more people there to help you out :)

This issue board is only related for technical issues related to the javascript SDK
