### ISSUE TITLE
Moralis.Plugins.opensea.createBuyOrder({....}) have issue with trigger signer is missing or undefined

### ISSUE THREAD

**Issue by RizwanAhmad-dev** [MoralisWeb3/Moralis-JS-SDK#280]
## New Bug Report
createBuyOrder is not working so I tried to look into node_modules, and I get to see that in file MoralisWeb3.js at line 1063

` if (!(!triggersArray[i].signer || triggersArray[i].signer)) {
                            _context13.next = 22;
                            break;
                          }`
                          
 That is a falsey statement and it will never go inside the if block 
 after fixing that I get new error  - 
 _reponse.wait() is not a function in MoralisWeb3.js at line -1082
 ` case 24:
                          _response = _context13.sent;

                          if (!((_triggersArray$i9 = triggersArray[i]) !== null && _triggersArray$i9 !== void 0 && _triggersArray$i9.shouldAwait)) {
                            _context13.next = 29;
                            break;
                          }

                          _context13.next = 28;
                          return _response.wait();`
                          
  Please help me with this
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Environment

Server

- Moralis server version: `FILL_THIS_OUT`

Client

- Moralis SDK version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Browser: `FILL_THIS_OUT`

**Comment by ErnoW** [comment]
Closing this issue as it's not relevant anymore since v2
