### ISSUE TITLE
Types: Missing .wait() method in ExecuteFunctionSendResult

### ISSUE THREAD

**Issue by xumepadismal** [MoralisWeb3/Moralis-JS-SDK#302]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

According to the [docs](https://docs.moralis.io/moralis-server/web3/web3#example-of-calling-a-write-contract-method) there is a `wait` method in response to `Moralis.executeFunction` and it indeed present in runtime, all good.

However TypeScript complains this method does not exist even if response type is asserted to `as Moralis.ExecuteFunctionSendResult`

Digging a bit into Moralis typings I found that

```ts
type EthersTransaction = import('ethers').Transaction;
```

which looks wrong to me. I think it should be changed to

```ts
type EthersTransaction = import('ethers').providers.TransactionResponse;
```

which type is correct. btw, even Moralis docs insists that "You will get back a [transaction response from Ethers.js](https://docs.ethers.io/v5/api/providers/types/#providers-TransactionResponse), ..."

### Steps + code to reproduce

```ts
declare const tx: Moralis.ExecuteFunctionSendResult;
tx.wait(); // Property 'wait' does not exist on type 'Transaction'.

```

**Comment by ErnoW** [comment]
Closing this issue as it's not relevant anymore since v2
