### ISSUE TITLE
Moralis.Web3API.storage.uploadFolder missing parameter options.

### ISSUE THREAD

**Issue by andreas-hauschild-inacta** [MoralisWeb3/Moralis-JS-SDK#313]
### Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x ] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

It looks like that the API Endpoint  `Moralis.Web3API.storage.uploadFolder(options)` is broken, or the documentation is outdated.
The parameter `options` doesn't exists anymore (i use typescript). It was removed here: https://github.com/MoralisWeb3/Moralis-JS-SDK/pull/79/commits/8522e781e691718f44fbb3179ce79219ecf25d34#

### Actual Outcome

Can't use storage endpoint because i cant set the parameter

### Expected Outcome

Can set the parameter to upload my files

### Environment

Client

- Moralis SDK version: `"moralis": "^1.5.9"`
- Operating system: `Windows 11`
- Browser: `Chrome Version 100.0.4896.60 (Official Build) (64-bit)`

**Comment by Mdk2022** [comment]
Am working on how to set the dix

**Comment by harshrpg** [comment]
Do we know when will this be fixed?

**Comment by ErnoW** [comment]
Closing, as it already has been fixed (different repo now: https://github.com/MoralisWeb3/Moralis-JS-SDK-v1)
