### ISSUE TITLE
BscTestChain type has rogue space character

### ISSUE THREAD

**Issue by wormat** [MoralisWeb3/Moralis-JS-SDK#316]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

The type for `BscTestChain` gives one option as `" 0x61"` rather than `"0x61"`.

### Steps + code to reproduce

See current code on `main`: https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/1a39b11906d579922ee4c8306e530d5d4bbb441b/types/index.d.ts#L397

### Actual Outcome

I can't combine types as expected, eg `Moralis.Chains.BSC_TESTNET` with `Moralis.Chain`.

### Expected Outcome

Everything should use `"0x61"` not the incorrect string with a rogue space character.

### Environment

Server

- Moralis server version: n/a

Client

- Moralis SDK version: `1.5.9`
- Operating system: n/a
- Browser: n/a

### Logs

n/a

**Comment by ErnoW** [comment]
Thanks, this has been fixed in v1.10
