### ISSUE TITLE
Moralis.Web3API.storage.uploadFolder not set data in the axios

### ISSUE THREAD

**Issue by LeoTeng** [MoralisWeb3/Moralis-JS-SDK#318]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

The uploadFolder function set body, but AxiosRequestConfig "body"  parameter does not exist;
So get the exception "Missing files from body"
need update the code ,set body change to set data.

And the doc should be update, because of was wrong，the source code bodyParams type is "data".

![image](https://user-images.githubusercontent.com/4424575/163999014-29140a0a-6b9e-4734-9d9c-9f402af3164c.png)

![image](https://user-images.githubusercontent.com/4424575/163999667-f222aeee-5b58-490f-88c2-9b7f7bf81b6d.png)

### Environment

Server

- Moralis server version: `0.0.369`

Client

- Moralis SDK version: `1.5.9"`
- Operating system: `Window 10`
- Browser: `Chrome`

**Comment by ErnoW** [comment]
Thanks, this has been fixed in v1.10
