### ISSUE TITLE
Can't create sell order

### ISSUE THREAD

**Issue by nikkakiffar** [MoralisWeb3/Moralis-JS-SDK#324]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I try to create new sell order in React app, but I get "Your wallet failed to sign your order correctly. Try a different wallet!".

### Steps + code to reproduce

            const createSellOrder = async () => {
		const expirationTime = Math.round(Date.now() / 1000 + 60 * 60 * 24);
		const startAmount = 1000;
		const endAmount = 100;

		await Moralis.Plugins.opensea.createSellOrder({
			network: "testnet",
			tokenAddress: "0xeBc81Ad820D43611E4BF4B03bE07E30ea1CB8224",
			tokenId: "1",
			tokenType: "ERC721",
			userAddress: "0x0f40f1f61C234e4Be3e14021c4EE77B76Da19580",
			startAmount,
			endAmount,
			expirationTime: startAmount > endAmount && expirationTime, // Only set if you startAmount > endAmount
		});

		console.log("Create Sell Order Successful");
	};

### Actual Outcome

I get a request to subscribe, then subscribe it and after that I have error: "Your wallet failed to sign your order correctly. Try a different wallet!".

<img width="790" alt="image" src="https://user-images.githubusercontent.com/39290876/166103989-e05fc7d5-e5d1-4291-849e-6fffb34cae1e.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/39290876/166103972-9edac43c-3b65-4224-bd18-7045a57a43a8.png">

### Expected Outcome

"Create Sell Order Successful" in the console without errors.

### Environment

Server

- Moralis server version: `0.0.369`

Client

- Moralis SDK version: `0.0.104`
- Operating system: `MacOS Monterey`
- Browser: `Chrome version 100.0.4896.127`

**Comment by ErnoW** [comment]
Closing issue as it's not relevant anymore, see https://docs.moralis.io/docs/self-hosted-moralis-server
