### ISSUE TITLE
Typescript: some fields are missing in the return type of getTokenIdMetadata

### ISSUE THREAD

**Issue by baocancode** [MoralisWeb3/Moralis-JS-SDK#327]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

Some fields such as owner_of or token_hash can be seen in the response of getTokenIdMetadata, but do not appear in the type definition.

### Steps + code to reproduce

```
const nft = await Moralis.Web3API.token.getTokenIdMetadata({
  address: '0x32895105b3a65da694c63a3f5f7347d5ebf07f07',
  token_id: '6363',
})

const owner = nft.owner_of // Typescript error: Property 'owner_of' does not exist on type ...
const tokenHash = nft.token_hash // Typescript error: Property 'token_hash' does not exist on type ...
```

### Actual Outcome

The code still works, but Typescript complains about the types.

### Expected Outcome

The code should not raise Typescript errors.

### Environment

Server

- Moralis server version: 0.0.374

Client

- Moralis SDK version: 1.6.0
- Operating system: Windows
- Browser: N/A, ran in Node.js 16.15.0

### Logs

N/A

**Comment by Mdk2022** [comment]
I moved my file from my phone to the computer and I am finding it difficult
to import them back.

**Comment by alexnguyennz** [comment]
As a workaround, in the `web3Api.d.ts` file in moralis/types/generated under the `nft` object, you can add the types manually:

```
owner_of: string;
token_hash: string;
```

**Comment by aliskhanoff** [comment]
The same thing with tokens
![image](https://user-images.githubusercontent.com/41637477/172132996-af14943f-c27b-47f8-b68b-8fe06582428c.png)

**Comment by ErnoW** [comment]
Fixed in https://github.com/MoralisWeb3/Moralis-JS-SDK-v1
