### ISSUE TITLE
Add redirectURI at magicLink

### ISSUE THREAD

**Issue by kodandy** [MoralisWeb3/Moralis-JS-SDK#347]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Cannot set redirectURI in authenticate when using magicLink.

### Feature / Enhancement Description

- Use `/src/Web3Connector/MagicWeb3Connector.js` to take over redirectURI.
- Add an entry for redirectURI to magic.auth.loginWithMagicLink.

### Example Use Case

If you want to set the redirectURI for authentication using magic.

### Alternatives / Workarounds

None.

**Comment by ErnoW** [comment]
It is now possible to add all Magic arguments, and we will pass it through to the magic-sdk.

This is implemented in v1.10
