### ISSUE TITLE
Add showUI parameter at MagicLink

### ISSUE THREAD

**Issue by fokindmitr** [MoralisWeb3/Moralis-JS-SDK#350]
### Checklist

- :white_check_mark: I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- :white_check_mark: I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Cannot prevent magicLink from shoving the popup when login with Moralis.

### Feature / Enhancement Description

Allow users to pass boolean `showUI`. Set default value to `true` in /src/Web3Connector/MagicWeb3Connector.js 
Pass `showUI` value to magic.auth.loginWithMagicLink. e.g. magic.auth.loginWithMagicLink({email, showUI})

### Example Use Case

```
const user = await Moralis.authenticate({ 
  provider: "magicLink",
  email: "example@email.com",
  apiKey: "pk_xxxxx",
  network: "kovan",
  showUI: false
})
```

**Comment by ErnoW** [comment]
It is now possible to add all Magic arguments, and we will pass it through to the magic-sdk.

This is implemented in v1.10
