### ISSUE TITLE
Better support for large file uploads to IPFS

### ISSUE THREAD

**Issue by ChrisBellew** [MoralisWeb3/Moralis-JS-SDK#353]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

When creating a `Moralis.File` instance, the data of the file can be provided as any of the following types
```
number[] | { base64: string } | { size: number; type: string } | { uri: string }
```
The `{ base64: string }` and `{ uri: string }` are text representations of the data. For binary files this can inflate the size of the file considerably. I believe `{ size: number; type: string }` are suited to using `File` uploads in the browser.

The choice for uploading binary data from nodejs without representing it as base64 is to use `number[]`. This allows us to provide an array of bytes. This is actually worse because each byte is represented as 8 bytes because that's the size of a `number` in nodejs.

### Feature / Enhancement Description

It would be great it there was a possibility to provide a `Buffer` or even better a `ReadableStream` because then a file could be streamed and buffered from another location without having it all present in memory at any time.

Thanks for the library!
Chris

**Comment by ErnoW** [comment]
Now it's possible to use Moralis as a self-hosted server and you can configure all internal logic yourself. You can use  v2+ on your server, or check the migration guide to a self-hosted server: https://docs.moralis.io/docs/self-hosted-moralis-server
