### ISSUE TITLE
Switch Network Functionality in WalletConnect Connector

### ISSUE THREAD

**Issue by YosephKS** [MoralisWeb3/Moralis-JS-SDK#449]
## New Feature Request

Seems like currently there's no `switchNetwork` function in WC connector, which makes it impossible for user to switch chain when they're using WC 

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

**Comment by ErnoW** [comment]
@YosephKS Do you know if this is at all supported by WalletConnect?

For metamask, they have their own function implemented that we can call to use this. But as far as I know this is not implemented in WalletConnect. Without them supporting this functionality, we cannot trigger chain changes via WalletConnect.

**Comment by YosephKS** [comment]
> @YosephKS Do you know if this is at all supported by WalletConnect?
> 
> For metamask, they have their own function implemented that we can call to use this. But as far as I know this is not implemented in WalletConnect. Without them supporting this functionality, we cannot trigger chain changes via WalletConnect.

Hmmm interesting I thought I see it somewhere in the docs, but can't find it now. Interestingly they have `chainChanged` listener, but cannot change chain itself.

I guess will have to close this one for now
