### ISSUE TITLE
Get value from mapping of arrays using runContractFunction

### ISSUE THREAD

**Issue by stpoa** [MoralisWeb3/Moralis-JS-SDK#450]
### Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I have a public mapping in my Solidity code:

```
  mapping(address => VestingWallet[]) public vestingWallets;
```

I want to read a value by giving it an address and index.
```
      runContractFunction<string>({
        functionName: 'fixedVestingWallets',
        params: { '': address, '': index },
      })
```
But as you probably know, you cannot have object with 2 same key names `''`. I even tried to change abi to add name to these params, but it didn't help. How to pass these params to get result?

### Steps + code to reproduce

Create contract similar to above, deploy, try running the method.

**Comment by alexnguyennz** [comment]
You can post on https://forum.moralis.io/ with this issue with more details like your contract code.

**Comment by ErnoW** [comment]
Yes, the moralis forums is a better place for asking these kind of support questions. Will close this issue as it is not related to the sdk codebase.
