### ISSUE TITLE
`Moralis.Chains` type mismatch

### ISSUE THREAD

**Issue by helloheesu** [MoralisWeb3/Moralis-JS-SDK#463]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

`Moralis.Chains`'s interface and its actual implentation don't match

Here it has a property named `ETH_MAINET`
https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/490821f6bcb1a81ce282a164814e450370eba5f0/types/index.d.ts#L1907

but its actual definition has a property named `ETH_MAINENT`
https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/490821f6bcb1a81ce282a164814e450370eba5f0/src/Chains.js#L2

### Steps + code to reproduce & Actual Outcome

When I try to use `Moralis.Chains.ETH_MAINET`, it returns `undefined`
while `Moralis.Chains.ETH_MAINENT` returns `"0x1"`, but with type error.

### Expected Outcome

Either `Moralis.Chains.ETH_MAINET` or `Moralis.Chains.ETH_MAINENT` should return valid value without any error.

### Environment

Client

- Moralis SDK version: `1.8.0`
- Operating system: `OS X 12.4`
- Browser: `Chrome 102.0.5005.115`

### Logs

N/A

**Comment by yocontra** [comment]
Also - this appears to be typo'd, it should be MAINNET (polygon is POLYGON_MAINNET)

**Comment by ErnoW** [comment]
Thanks, these issues have been fixed in v1.10
