### ISSUE TITLE
getNFTsForContract no longer works.

### ISSUE THREAD

**Issue by thekesslereffect** [MoralisWeb3/Moralis-JS-SDK#479]
I get an empty response when I try to run the getNFTsForContract function. It was working fine 10 hours ago, so maybe something changed between then and now.

People recently unstaking from my contract and trying to restake the nfts arent showing up that they own them when using the getNFTsForContract function even though on polygonscan they show up as the owners and their nfts show up on opensea fine.

Also I can input the staking contract into the getNFTsForContract function and it shows all the nfts correctly in there. Just not when someone unstakes now. It was working fine before.

NFT Contract: 0x1aAA180d4C82aa7EAcEa1FAe8B09BbB8174Cbbf0
Staking Contract: 0x9963bc674e7D9c5259d5E0Bf1094d8D353f5dAA1

**Comment by thekesslereffect** [comment]
i just tried putting my staking contract as the user address and the getNFTsForContract function is showing old data. Nfts that it doesnt hold anymore

**Comment by ErnoW** [comment]
Hi, this is related to our Web3Api, and not related to the JS-SDK.

We have a team of people to help you at our forums: forum.moralis.io. Please reach out there so the correct person can reach out to you.
