### ISSUE TITLE
remove checkForSdkUpdates on production builds

### ISSUE THREAD

**Issue by matiyin** [MoralisWeb3/Moralis-JS-SDK#483]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

The current Moralis SDK version (1.8.1) has a 'feature' that checks if the latest SDK version is being used, otherwise displaying a console warning. Since this is calling `https://www.unpkg.com/moralis/package.json` which can be slow, my browser is stuck loading until this is done, in this example taking more than 8s. Although not render-blocking, Firefox still indicates a loading status until complete.

![image](https://user-images.githubusercontent.com/2891951/178207680-e9f077cb-fb48-4d87-99e9-861476264243.png)
![image](https://user-images.githubusercontent.com/2891951/178207785-42696cd9-54d3-4430-b41b-c1de11ba74d2.png)

The code:

https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/dd00f423c19a162a49b5206a92da0cbaa9568a38/src/utils.js#L96

### Feature / Enhancement Description

Although a 'nice' feature for development, it adds unnecessary load on a production environment and it should either be optional or automatically disabled when using `process.env.NODE_ENV === 'production'`

**Comment by ErnoW** [comment]
In v1.10 you can provide an option to `Moralis.start({disableVersionCheck: true})`.
This will skip this version check.

**Comment by matiyin** [comment]
Using Moralis-v1 1.11.0 with

```import { Moralis } from 'moralis-v1'

Moralis.start({
  serverUrl: process.env.VUE_APP_MORALIS_SERVER_URL,
  appId: process.env.VUE_APP_MORALIS_APP_ID,
  disableVersionCheck: true,
});

export { Moralis }
```

still gives a warning is console:

`Moralis: You are not using the latest version of the SDK. Please update it as soon as possible to enjoy the newest features. Most recent version: 2.0.3`
