### ISSUE TITLE
Nodejs TypeScript getContractEvents bodyParams is required

### ISSUE THREAD

**Issue by yuexuan** [MoralisWeb3/Moralis-JS-SDK#553]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Steps + code to reproduce
 getContractEvents: (options: operations["getContractEvents"]["parameters"]["query"] & operations["getContractEvents"]["parameters"]["path"]) => Promise<operations["getContractEvents"]["responses"]["200"]["content"]["application/json"] & defaultResponse<operations["getContractEvents"]["responses"]["200"]["content"]["application/json"]>>;

but:

abi (required): Event ABI (do not insert the ABI of the whole smart contract). ABI has a JSON format.

/** ABI of the specific event */
    requestBody: {
      content: {
        "application/json": { [key: string]: unknown };
      };
    };

Request Body cannot be used as a parameter.  I think this is bug.

at web3 api , the source is 'Web3Api.fetch({ endpoint: {"method":"POST","group":"native","name":"getContractEvents","url":"/:address/events","bodyParams":[{"key":"data","type":"set body","required":false}]}, params: options }'.

the bodyParams is fixed.  it can't update as a params.

### Actual Outcome

Invalid ABI

### Expected Outcome

I want the bodyParams  as params.

### Environment

Server

- Moralis server version: `v1.11.0`

I used typescrpt.

**Comment by ErnoW** [comment]
Closing, as not relevant anymore for his repo, and it has been fixed in https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/pulls
