### ISSUE TITLE
[Recommendation] Base Server UI on Material Design

### ISSUE THREAD

**Issue by mobilekosmos** [MoralisWeb3/Moralis-JS-SDK#7]
Material Design:
"Material is a design system – backed by open-source code – that helps teams build high-quality digital experiences."
https://material.io/

In my experience basing the UI on Material allows you to quickly come up with solutions without needing to reinvent the wheel each time you need a button, etc. It avoids discussions in the team like "I like that better, I like the other one better". It's like a lot of decissions get delegated to a system which is made by UI/UX experts, studied, tested, proven, et.c.

I came up with this after seeing this part of the server:
![image](https://user-images.githubusercontent.com/1061543/133912963-c879c77c-0fc4-49a4-8592-050013df91e3.png)

Knowing about Material Design I would say for example that the Material Solution for such an element is more intuitive:
![image](https://user-images.githubusercontent.com/1061543/133913028-3a52c739-3fea-4c30-9a59-ace106e35103.png)

![image](https://user-images.githubusercontent.com/1061543/133913029-19b2afd6-8313-4665-ba95-e627dbe92f8c.png)

Depending on what tech you are using there is [Material for Angula](https://material.angular.io/components/expansion/overview)r, [React ](https://mui.com/components/accordion/) etc.

Also the empty state of the servers list is a typical scenario which could be easily improved applying the [Material Principles for Empty States](https://material.io/design/communication/empty-states.html)

**Comment by mobilekosmos** [comment]
For example you delete server confirmation dialog:

![image](https://user-images.githubusercontent.com/1061543/133913396-f002d28c-383e-46d6-9e9f-af25608fe68a.png)

Have you decided by yourself how each element should look, how big, where, etc.? Using the [Material Alert Dialog](https://material.io/components/dialogs/web#alert-dialog) you would get all parameters decided for you. I for example find the Material Alert Dialog a better solution than yours using the close icon, I would prefer Cancel and Delete buttons as per Material Design. And this is what I mean in my post above, once you decide to use Material Design you implement all elements based on the Material documentation and that's it, no more thinking should we put the button here or there or better here, etc.

jm2c, ignore if you want to :)

**Comment by ivan-liljeqvist** [comment]
Thanks for suggestions we will carefully consider this, but this is not the correct repo for this as this has nothing to do with the SDK. Please write such suggestions in https://forum.Moralis.io. Thanks!
