### ISSUE TITLE
Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.1)

### ISSUE THREAD

**Issue by oconnorjoseph** [MoralisWeb3/Moralis-JS-SDK#706]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

Executing `signInWithMoralis` from `@moralisweb3/client-firebase-evm-auth` following this demo - https://github.com/MoralisWeb3/Moralis-JS-SDK/tree/main/demos/firebase-auth-ext - results in the following error:

![image](https://user-images.githubusercontent.com/47279098/192390469-be8dc2e2-9f5d-432e-8c93-3ac3499bcbe3.png)

This is only a problem with `"@moralisweb3/client-firebase-auth-utils": "2.5.7"` and `"@moralisweb3/client-firebase-evm-auth": "2.5.7"`. `signInWithMoralis` functions properly when using version `2.5.6`.

### Environment

Server

- Moralis server version: `v0.386`

Client

- `"@moralisweb3/client-firebase-auth-utils": "2.5.7"`
- `"@moralisweb3/client-firebase-evm-auth": "2.5.7"`
- Operating system: `MacOS`
- Browser: `Brave`

**Comment by ErnoW** [comment]
@oconnorjoseph Please check with version 2.5.8
