### ISSUE TITLE
[SERVER - IMPROVEMENT] Elaborate "deleting" text

### ISSUE THREAD

**Issue by mobilekosmos** [MoralisWeb3/Moralis-JS-SDK#8]
![image](https://user-images.githubusercontent.com/1061543/133913595-e5480af3-bfbb-48d5-9f56-59e20642cf3e.png)

When you delete a server you show the text "deleting". I would elaborate this and maybe use "Deleting, this may take some time" or ""Deleting, this may take up to xy".

**Comment by ivan-liljeqvist** [comment]
Thanks for suggestions we will carefully consider this, but this is not the correct repo for this as this has nothing to do with the SDK. Please write such suggestions in https://forum.Moralis.io. Thanks!
