### ISSUE TITLE
[SERVER - IMPROVEMENT] Add new server dialog

### ISSUE THREAD

**Issue by mobilekosmos** [MoralisWeb3/Moralis-JS-SDK#9]
1. For me it was strange that the add new server window remembers its state, if you close it and the select add new server again you get the same state as before leaving that window.
2. The **Select All Chains** UI element is shown despite the chains are not listed yet, also pressing this ui element leads to the chains being shown but not selection occurs, this is misleading:
![image](https://user-images.githubusercontent.com/1061543/133913848-6aa76acc-007e-467c-a499-19ebeac2393a.png)

3. I would recommend to making the Select All Chains element something like a toggle so you can unselect all again pressing on the same element.

4. The **Select Network** section is not prefilled at first, once you type the name of the server it gets prefilled, it should be already prefilled before I suppose?

**Comment by ivan-liljeqvist** [comment]
Thanks for suggestions we will carefully consider this, but this is not the correct repo for this as this has nothing to do with the SDK. Please write such suggestions in https://forum.Moralis.io. Thanks!
