### ISSUE TITLE
Type information for Moralis.EvmApi.nft.getNFTContractTransfers does not include all parameters exposed in API

### ISSUE THREAD

**Issue by psychob** [MoralisWeb3/Moralis-JS-SDK#903]
### Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [X] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [X] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description
Method: `Moralis.EvmApi.nft.getNFTContractTransfers` does not expose all parameters that API supports: https://docs.moralis.io/reference/getnftcontracttransfers. Namely: `from_block` and `to_block`

### Steps + code to reproduce

```typescript

    
import {
  GetNFTContractTransfersRequest,
} from '@moralisweb3/common-evm-utils';

const options: GetNFTContractTransfersRequest = {
  address: address,
  chain: chain,
  format: 'decimal',
  from_block: fromBlock,
  to_block: toBlock,
};

```

### Actual Outcome

```
xxx.ts:xx:7 - error TS2322: Type '{ address: string; chain: EvmChain; format: "decimal"; from_block: number; to_block: number; }' is not assignable to type 'GetNFTContractTransfersRequest'.
  Object literal may only specify known properties, and 'from_block' does not exist in type 'GetNFTContractTransfersRequest'.
```

**Comment by ErnoW** [comment]
It has been added. Note that parameters in the SDK are camelCase

```typescript
  // Option 1
  const transfers = await Moralis.EvmApi.nft.getNFTContractTransfers({
    chain: EvmChain.ETHEREUM,
    address: '0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85',
    fromBlock: 16000000,
    toBlock: 16500000,
  });
  console.log(transfers.result);

  // Option 2
  const transferOptions: GetNFTContractTransfersRequest = {
    chain: EvmChain.ETHEREUM,
    address: '0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85',
    fromBlock: 16000000,
    toBlock: 16500000,
  };

  const transfers2 = await Moralis.EvmApi.nft.getNFTContractTransfers(transferOptions);
  console.log(transfers2.result);
```
