### ISSUE TITLE
@moralisweb3/next keeps unrelated packages to be run in runtime `@solana/buffer-layout` and `ethereumjs-utils`

### ISSUE THREAD

**Issue by hskang9** [MoralisWeb3/Moralis-JS-SDK#947]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

@moralisweb3/next requires two external packages to be installed in plain next.js application boilerplate. One is `ethereumjs-utils` and `@solana/buffer-layout`. What's worse, `@solana/buffer-layout` requires deprecated version where it asks `index.js` file to initialize the Moralis object. Newest version of `@solana/buffer-layout` somehow replaced from `index.js` to `Layout.js`. This is nonsense when its package name is literally buffer-layout, but it is Solana, what do you expect. I hope @moralisweb3/next could put these packages in dev-dependancies as they should not be required to be needed in runtime at all. I am actually surprised as well Moralis team cannot handle dev dependancies on releasing package. Now I see why, you guys are using monorepo. I am forking this.

### Steps + code to reproduce

Follow guide in https://docs.moralis.io/authentication-api/how-to-sign-in-with-metamask?utm_source=blog&utm_medium=post&utm_campaign=How%2520to%2520Connect%2520MetaMask%2520to%2520Website%2520with%2520NextJS

### Actual Outcome

<img width="1222" alt="Screen Shot 2023-01-05 at 3 23 34 PM" src="https://user-images.githubusercontent.com/12888144/210771431-aedb4f78-305a-4ea1-805e-a710231ea9a7.png">

### Expected Outcome

This should compile without Module not found error. 

### Environment

Here is my related dependancies for the dapp.
```
"dependencies": {
    "@moralisweb3/common-evm-utils": "^2.11.0",
    "@moralisweb3/next": "^2.11.0",
    "@solana/buffer-layout": "^4.0.1",
    "@tailwindcss/typography": "0.5.2",
    "ethereumjs-util": "^7.1.5",
    "ethers": "^5.7.2",
    "moralis": "^2.11.0",
    "next": "12.2.5",
    "next-auth": "^4.18.7",
    "postcss": "8.4.12",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "6.15.1",
    "stream": "^0.0.2",
    "tailwindcss": "3.0.23",
    "wagmi": "^0.10.4"
  },
```

Server

- Moralis server version: `NOT_RELATED`

Client

- Moralis SDK version: `2.11.0`
- Operating system: `MAC OS`
- Browser: `Google Chrome`

**Comment by Juici** [comment]
> @Juici why would you break Moralis by changing the package entry point file? 
> 

I didn't? The only contribution I have to @solana/buffer-layout is to fix a type hint.

**Comment by hskang9** [comment]
oh...? then who manages this repo? whoever did this, renaming an `index.js` entry point file into `Layout.js` when the package name literally says `buffer-layout`, is like Elon making Boring project when there is already an underground tunnel. I don't see anyone who managed this repository could not make issues of this.

**Comment by hskang9** [comment]
Why can't @solana-labs even check whether their published `buffer-layout` package has dependancies included after publishing? This is just a terrible job of managing `tsconfig.json` here. https://github.com/solana-labs/buffer-layout/blob/72946cea49eb999dbdd04281c6946adb873be4f1/tsconfig.json#L18 Why the hell would they use Typescript when they cannot even compile right?

**Comment by hskang9** [comment]
@jstarry set tsconfig.json's exclude to remove `node_modules` option then publish on the next version or this api will be wrecked. All these breakdowns are happening because of you. https://github.com/solana-labs/buffer-layout/commit/476627934922507edd0d1fab8ed44bb6eddc791b

**Comment by ivan-liljeqvist** [comment]
@ErnoW and team will check :)

**Comment by b4rtaz** [comment]
I'm looking at it.

**Comment by b4rtaz** [comment]
I cannot reproduce it. I've tested [this demo](https://github.com/MoralisWeb3/Moralis-JS-SDK/tree/main/demos/nextjs) outside of our repo, and it seems to work properly. Even I've set your dependency list from your first post. 

Could you share your version of npm/yarn/node?

**Comment by hskang9** [comment]
For me, auth worked, problem happens when the Moralis api interacts with interacting with the server.

npm version is 8.19.2
yarn version is 1.22.19
node version is v18.12.1

**Comment by hskang9** [comment]
We just need to wait for @jstarry to fix his typescript configuration or sever out his package.

**Comment by b4rtaz** [comment]
> This is because problem happens when the Moralis api interacts with interacting with Solana's web3.js library.

What operation cases this?

I've added `useSolPortfolio()` and `useSolBalance()` in the [demo app](https://github.com/MoralisWeb3/Moralis-JS-SDK/tree/main/demos/nextjs) (those methods internally use `@solana/web3.js`), and still don't see any error.

Could you download [the demo](https://github.com/MoralisWeb3/Moralis-JS-SDK/tree/main/demos/nextjs) and try to run it?

**Comment by steveluscher** [comment]
Message received! Solana's happy to help here. I'll work on it with you in https://github.com/solana-labs/buffer-layout/pull/5.
