### ISSUE TITLE
@moralisweb3/next does not send API request to its fixed endpoint, instead it sends request to localhost

### ISSUE THREAD

**Issue by hskang9** [MoralisWeb3/Moralis-JS-SDK#948]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

MoralisNextApi is not sending API request to Moralis api endpoint. Instead, it sends requests to localhost.

### Steps + code to reproduce

Follow the guide and run it.

### Actual Outcome

<img width="1709" alt="Screen Shot 2023-01-05 at 6 23 00 PM" src="https://user-images.githubusercontent.com/12888144/210802124-b3debcc7-b928-48da-9ecb-2d6cda7af358.png">

### Expected Outcome

Native balance of an account in ether decimal

### Environment

https://github.com/MoralisWeb3/demo-apps/tree/main/nextjs

Server

- Moralis server version: `I DO NOT KNOW`

Client

- Moralis SDK version: `2.9.0`
- Operating system: `MAC OS`
- Browser: `Google Chrome`

**Comment by FedericoAmura** [comment]
Hi @hskang9 
Thanks for letting us know. We are trying to reproduce it on our end

Could you let us know where are you running the demo? Is it local or you have it deployed somewhere?
Any other detail that might be extra to following our instructions would be helpful too. Also server logs

I succeded in reproducing this error by setting up an incorrect `MORALIS_API_KEY` in the `.env.local` file. Please verify that too. There are several Moralis keys and the one that is needed there is Web3 Api Key. You can also get it in your [Web3 APIs](https://admin.moralis.io/web3apis) dashboard

**Comment by hskang9** [comment]
oh local keys... sorry I did not notice that.

**Comment by hskang9** [comment]
Now all keys are pointing to one single web3 api key. https://docs.moralis.io/web3-data-api/get-your-api-key

**Comment by hskang9** [comment]
and yes, it does not work even if I have one correct api key.

**Comment by hskang9** [comment]
Key is not the point, MoralisNextApi is sending request to localhost endpoint when it is supposed to send request to Moralis server.

**Comment by hskang9** [comment]
Here, this sets api endpoint to localhost. It seems that I have to run a specific server related to Moralis API? I think you need to add another section to set the server to run with next.js. 
https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/78fb808732d9c05c3df05223598acc6181655d8e/packages/next/src/utils/fetchers/fetcher.ts#L19

**Comment by hskang9** [comment]
@Y0moo pointing endpoint to its webapp API routes does not work. Why did you do that? Is there another component that has to be run together with NextJS? Why is this tutorial ever be released?

**Comment by hskang9** [comment]
I notice this requires a specific setup which is different from other nextjs setting. I need to check with https://github.com/ethereum-boilerplate/ethereum-boilerplate

**Comment by hskang9** [comment]
running app points to the right direction, but running storybook does not point to right api. I think this is rather related to storybook's problem not being able to run moralis api.
