### ISSUE TITLE
PHI Network Smart Chain Support

### ISSUE THREAD

**Issue by Phinetwork** [MoralisWeb3/Moralis-JS-SDK#965]
## New Feature Request
https://chainlist.org/chain/144
https://phi.network 
https://doc.phi.network 

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

**Comment by ErnoW** [comment]
As mentioned in https://github.com/MoralisWeb3/docs/pull/4 PHI is not a supported chain in our APIs. 
If this is a feature request, then please submit at https://roadmap.moralis.io/
